# Generated by Django 4.1.1 on 2022-10-13 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=1, max_length=10, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
