# Generated by Django 4.1.1 on 2022-10-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_type_alter_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialist',
            field=models.CharField(blank=True, choices=[('nose and ear', 'nose and ear'), ('tooth', 'tooth'), ('heart', 'hreat'), ('skin', 'skin')], max_length=20, null=True, verbose_name='doctor at'),
        ),
    ]
